version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./static:/app/static

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data: