version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: ["/entrypoint.sh"]

  redis:
    image: "redis:alpine"
